## Frisch aus dem Trockner, gut für die *confidence*

```{r eval = FALSE, tidy=FALSE}

#computes a confidence interval from a sample:
generate_confidence_interval <- function(sample_vector) {
  #check if input is a numerical vector with length >= 2 
  #(otherwise standard deviation cannot be computed)
  checkmate::assert_numeric(sample_vector,
                 any.missing = FALSE,
                 min.len = 2)
  
  #compute confidence interval
  sample_size <- length(sample_vector)
  sample_mean <- mean(sample_vector)
  sample_sd <- sd(sample_vector)
  interval_half_width <- 1.96 * sample_sd / sqrt(sample_size)
  interval <- c(sample_mean - interval_half_width, 
                sample_mean + interval_half_width)
  return(interval)
}

#try out for some values
generate_confidence_interval(runif(100))
generate_confidence_interval(runif(100)^2)
generate_confidence_interval(c(NA, NA))
generate_confidence_interval(2)
generate_confidence_interval(c("b", "c"))

``` 

Bei so abscheulichem "copy-paste-modify" Code wie dem hier sollten Sie direkt schweiß*nasse* Hände bekommen, denn "**w**rite **e**verything **t**wice" ist der sichere Weg ins Verderben.  
Bringen Sie die Sache also in *trockene* Tücher in dem Sie den redundanten Code als Funktion einkapseln und diese dann wiederholt aufrufen -- **d**on't **r**epeat **y**ourself !!11!

*Hinweis 1:* In RStudio ist das besonders besonders einfach -- markieren Sie den Code den Sie einkapseln möchten und drücken Sie `<Strg + Alt + X>` (oder klicken Sie im Menü "Code" auf "Extract Function").  
*Hinweis 2:* Der Code oben ist nicht nur redundant (bäh!), er ist auch nicht konsistent nach dem Styleguide formatiert (pfui!). Bringen Sie das in Ihrer Lösung in Ordnung, entweder mit flinken Fingern durch Ihr geschultes Auge und Ihren wachen Verstand, oder, wesentlich einfacher & zuverlässiger, indem Sie die RStudio-Addins des `styler`-Pakets zum Umformatieren benutzen.
